### ISSUE TITLE
broken dependencies 

### ISSUE THREAD

**Issue by MeirionHughes** [agentframework/webstack#5]
Looks like there has been some refactoring of "agentstack" that hasn't trickle into this project. fresh install of this template doesn't work.

**Comment by e2tox** [comment]
There are some breaking changes in the latest template:

OLD:
    const App = require('./layouts/app');

NEW: 
    import App from './layouts/app.vue';

Since `vue init` will cache the template. Please run these command to update your local template

    rm -rf ~/.vue-templates/agentframework-webstack

Now you are ready to use the new template:

    vue init agentframework/webstack your-project
